[2022-08-10 15:22:05,900] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/sport C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py rt:0.0029506683349609375 Unauthorized Access 
NoneType: None
[2022-08-10 15:22:20,198] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/sport?key=KfmH9cDCXnYXhXk7ne6MF6XtgJ7Ea7XA27 C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py rt:0.0 Unauthorized Access 
NoneType: None
[2022-08-10 15:22:26,091] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/sport?key=KfmH9cDCXnYXhXk7ne6MF6XtgJ7Ea7XA27 C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py rt:0.0020263195037841797 Unauthorized Access 
NoneType: None
[2022-08-10 15:22:45,125] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/politic?key=KfmH9cDCXnYXhXk7ne6MF6XtgJ7Ea7XA27 C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py rt:0.0 Unauthorized Access 
NoneType: None
[2022-08-10 15:23:09,501] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/sport?key=KfmH9cDCXnYXhXk7ne6MF6XtgJ7Ea7XA2 C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py rt:0.03775835037231445 Exception on /news/api/sport [GET]
Traceback (most recent call last):
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py", line 11, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\api\controller.py", line 78, in get_sport_news
    sport_news = ApiUtils.get_sport_news()
TypeError: get_sport_news() missing 1 required positional argument: 'self'
[2022-08-10 15:23:21,934] ERROR 127.0.0.1 GET HTTP/1.1 http://127.0.0.1:5000/news/api/magazine?key=KfmH9cDCXnYXhXk7ne6MF6XtgJ7Ea7XA2 C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py rt:0.7481706142425537 Exception on /news/api/magazine [GET]
Traceback (most recent call last):
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\decorators\api_decorators.py", line 11, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\application\api\controller.py", line 56, in get_magazine_news
    return jsonify(response.__dict__)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Users\Kubilay Peker\anaconda3\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\Kubilay Peker\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Kubilay Peker\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Kubilay Peker\Desktop\new_Api\HaberTakipApi\new_venv\lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Users\Kubilay Peker\anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable
